name: Api Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kimpl"
          heroku_email: "felipe.santos@ccc.ufcg.edu.br"
          appdir: "api"
        env:
          HD_MONGO_URL: ${{secrets.MONGO_URL}}